# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_fields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='data_cad',
        ),
    ]
