# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_fields', '0002_remove_form_data_cad'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='data_cad',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 9, 21, 4, 42, 471181, tzinfo=utc)),
        ),
    ]
