# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_fields', '0003_form_data_cad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='data_cad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
