# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_fields', '0004_auto_20160709_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='select_item',
            name='form',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='personal_fields.Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text_area',
            name='form',
            field=models.ForeignKey(default=datetime.datetime(2016, 7, 10, 0, 57, 42, 486704, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='personal_fields.Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text_field',
            name='form',
            field=models.ForeignKey(default=datetime.datetime(2016, 7, 10, 0, 57, 50, 829402, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='personal_fields.Form'),
            preserve_default=False,
        ),
    ]
