# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_fields', '0005_auto_20160710_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_item',
            name='form',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal_fields.Form'),
        ),
    ]
