# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_fields', '0006_auto_20160710_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='data_cad',
        ),
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item_field',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item_field',
            name='select_item',
        ),
        migrations.RemoveField(
            model_name='item_field',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='select_item',
            name='form',
        ),
        migrations.RemoveField(
            model_name='select_item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='text_area',
            name='form',
        ),
        migrations.RemoveField(
            model_name='text_area',
            name='name',
        ),
        migrations.RemoveField(
            model_name='text_area',
            name='value',
        ),
        migrations.RemoveField(
            model_name='text_field',
            name='form',
        ),
        migrations.RemoveField(
            model_name='text_field',
            name='name',
        ),
        migrations.RemoveField(
            model_name='text_field',
            name='value',
        ),
    ]
