# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_fields', '0007_auto_20160710_0132'),
    ]

    operations = [
    ]
